config/routes.rb
Travel::Application.routes.draw do
  
  get "trips/test"
  get "users/filter"

  resources :hot_spots
  resources :notes
  resources :accommodations
  resources :destinations
  resources :trips

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pages#home'
  get "about" => 'pages#about'
  get "all" => 'users#show'
   

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :description, :subject, :trip_id
  validates :subject, presence: true
  belongs_to :user
  belongs_to :trip
  validates :user_id, presence: true
  validates :trip_id, presence: true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!
  # GET /notes
  # GET /notes.json

  def index
    @notes = current_user.notes.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = current_user.notes.find(params[:id])
    @trip_idn = @note.trip_id
    @trip = current_user.trips.find(@trip_idn)
    @trip_description = current_user.trips.find(@trip_idn).description
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = current_user.notes.new
    @trips = current_user.trips

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = current_user.notes.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = current_user.notes.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.input :description, as: :text, input_html: {rows: '5'} %>
    <%= f.association :trip, collection: current_user.trips.all, label_method: :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/notes/_note.html.erb
<div class="box" class="@note_idn">
	<p><span class="note_label">Note:</span> <b><%= note.subject %></b>
	</p>

	<p>
		<%= note.description %>
	</p>

	<p>
		<% trip_idn = current_user.trips.find(note.trip_id) %>
		<em>Associated with <b><%= link_to  current_user.trips.find(trip_idn).description, trip_idn %></b></em>
	</p>
	
	<p>
		<% if current_user == note.user %>
			<%= link_to 'Show', note %> |
			<%= link_to 'Edit', edit_note_path(note) %> |
			<%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>
</div>

app/views/notes/edit.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">

			<h2>Editing Note</h2>

			<%= render 'form' %>

			<%= link_to 'Show', @note %> |
			<%= link_to 'Back', notes_path %>

		</div>
	</div>
</div>

app/views/notes/index.html.erb
<div id="container">
  <%= render @notes %>
</div>

app/views/notes/new.html.erb
<div class="row">
	<div class="span7 offset1">
		<div class="well">

			<h2>New Note</h2>

			<%= render 'form' %>

			<%= link_to 'Back', notes_path %>

		</div>
	</div>
</div>

app/views/notes/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			  <b>Subject:</b>
			  <%= @note.subject %>
			</p>

			<p>
			  <b>Description:</b>
			  <%= @note.description %>
			</p>
			<p>
				<em>Associated with <b><%= link_to @trip_description, @trip %></b><br />
					Created by <%= @note.user.username %></em>
			</p>
			<p>
				<% if current_user == @note.user %>
					<%= link_to 'Edit', edit_note_path(@note) %> |
					<%= link_to 'Back to Notes', notes_path %>
					<% end %>
			</p>
		</div>
	</div>
</div>