config/routes.rb
Travel::Application.routes.draw do
  
  get "trips/test"
  get "users/filter"

  resources :hot_spots
  resources :notes
  resources :accommodations
  resources :destinations
  resources :trips

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pages#home'
  get "about" => 'pages#about'
  get "all" => 'users#show'
   

end

app/models/hot_spot.rb
class HotSpot < ActiveRecord::Base
  attr_accessible :address, :category, :description, :hours, :link, :other, :phone, :title, :trip_id
  belongs_to :user
  belongs_to :trip
  validates :user_id, presence: true
  validates :trip_id, presence: true
end

app/controllers/hot_spots_controller.rb
class HotSpotsController < ApplicationController
  before_filter :authenticate_user!
  # GET /hot_spots
  # GET /hot_spots.json
  def index
    @hot_spots = current_user.hot_spots.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hot_spots }
    end
  end

  # GET /hot_spots/1
  # GET /hot_spots/1.json
  def show
    @hot_spot = current_user.hot_spots.find(params[:id])
    @trip_idn = @hot_spot.trip_id
    @trip = current_user.trips.find(@trip_idn)
    @trip_description = current_user.trips.find(@trip_idn).description

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hot_spot }
    end
  end

  # GET /hot_spots/new
  # GET /hot_spots/new.json
  def new
    @hot_spot = current_user.hot_spots.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hot_spot }
    end
  end

  # GET /hot_spots/1/edit
  def edit
    @hot_spot = current_user.hot_spots.find(params[:id])
  end

  # POST /hot_spots
  # POST /hot_spots.json
  def create
    @hot_spot = current_user.hot_spots.new(params[:hot_spot])

    respond_to do |format|
      if @hot_spot.save
        format.html { redirect_to @hot_spot, notice: 'Hot spot was successfully created.' }
        format.json { render json: @hot_spot, status: :created, location: @hot_spot }
      else
        format.html { render action: "new" }
        format.json { render json: @hot_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hot_spots/1
  # PUT /hot_spots/1.json
  def update
    @hot_spot = current_user.hot_spots.find(params[:id])

    respond_to do |format|
      if @hot_spot.update_attributes(params[:hot_spot])
        format.html { redirect_to @hot_spot, notice: 'Hot spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hot_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hot_spots/1
  # DELETE /hot_spots/1.json
  def destroy
    @hot_spot = current_user.hot_spots.find(params[:id])
    @hot_spot.destroy

    respond_to do |format|
      format.html { redirect_to hot_spots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hot_spots_helper.rb
module HotSpotsHelper
end

app/views/hot_spots/_form.html.erb
<%= simple_form_for(@hot_spot, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :category, collection: ["Food", "Entertainment", "Sights", "Shopping", "Resource"], prompt: " " %>
    <%= f.input :address %>
    <%= f.input :phone %>
    <%= f.input :hours %>
    <%= f.input :description %>
    <%= f.input :link %>
    <%= f.input :other, as: :text, input_html: { rows: '3'} %>
    <%= f.association :trip, collection: current_user.trips.all, label_method: :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hot_spots/_hot_spot.html.erb
<div class="box">
	<p><span class="hot_spot_label">Hot Spot:</span> <b><%= hot_spot.title %></b>
      </p>

      <p>
        <% if !hot_spot.category.empty? %>
          <b>Category:</b>
          <%= hot_spot.category %>
        <% end %>
      </p>

      <p>
        <% if !hot_spot.address.empty? %>
          <b>Address:</b>
          <%= hot_spot.address %>
        <% end %>
      </p>

      <p>
        <% if !hot_spot.phone.empty? %>
          <b>Phone:</b>
          <%= hot_spot.phone %>
        <% end %>
      </p>

      <p>
        <% if !hot_spot.hours.empty? %>
          <b>Hours:</b>
          <%= hot_spot.hours %>
        <% end %>
      </p>

      <p>
        <% if !hot_spot.description.empty? %>
          <b>Description:</b>
          <%= hot_spot.description %>
        <% end %>
      </p>

      <p>
        <% if !hot_spot.link.empty? %>
          <b>Link:</b>
          <%= hot_spot.link %>
        <% end %>
      </p>

      <p>
        <% if !hot_spot.other.empty? %>
          <b>Other:</b>
          <%= hot_spot.other %>
        <% end %>
      </p>
      <p>
        <% trip_idn = current_user.trips.find(hot_spot.trip_id) %>
        <em>Associated with <b><%= link_to  current_user.trips.find(trip_idn).description, trip_idn %></b></em>
      </p>

	<p>
		<% if current_user == hot_spot.user %>
			<%= link_to 'Show', hot_spot %> |
			<%= link_to 'Edit', edit_hot_spot_path(hot_spot) %> |
			<%= link_to 'Destroy', hot_spot, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>
</div>

app/views/hot_spots/edit.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">

			<h2>Editing Hot Spot</h2>

			<%= render 'form' %>

			<%= link_to 'Show', @hot_spot %> |
			<%= link_to 'Back', hot_spots_path %>

		</div>
	</div>
</div>

app/views/hot_spots/index.html.erb
<div id="container">
  <%= render @hot_spots %>
</div>

app/views/hot_spots/new.html.erb
<div class="row">
	<div class="span7 offset1">
		<div class="well">

			<h2>New Hot Spot</h2>

			<%= render 'form' %>

			<%= link_to 'Back', hot_spots_path %>

		</div>
	</div>
</div>

app/views/hot_spots/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">

      <p>
        <b>Title:</b>
        <%= @hot_spot.title %>
      </p>

      <p>
        <% if !@hot_spot.category.empty? %>
          <b>Category:</b>
          <%= @hot_spot.category %>
        <% end %>
      </p>

      <p>
        <% if !@hot_spot.address.empty? %>
          <b>Address:</b>
          <%= @hot_spot.address %>
        <% end %>
      </p>

      <p>
        <% if !@hot_spot.phone.empty? %>
          <b>Phone:</b>
          <%= @hot_spot.phone %>
        <% end %>
      </p>

      <p>
        <% if !@hot_spot.hours.empty? %>
          <b>Hours:</b>
          <%= @hot_spot.hours %>
        <% end %>
      </p>

      <p>
        <% if !@hot_spot.description.empty? %>
          <b>Description:</b>
          <%= @hot_spot.description %>
        <% end %>
      </p>

      <p>
        <% if !@hot_spot.link.empty? %>
          <b>Link:</b>
          <%= @hot_spot.link %>
        <% end %>
      </p>

      <p>
        <% if !@hot_spot.other.empty? %>
          <b>Other:</b>
          <%= @hot_spot.other %>
        <% end %>
      </p>

      <p>
        <em>Associated with <b><%= link_to @trip_description, @trip %></b><br />
          Created by <%= @hot_spot.user.username %></em>
      </p>

      <p>
        <% if current_user == @hot_spot.user %>
          <%= link_to 'Edit', edit_hot_spot_path(@hot_spot) %> |
          <%= link_to 'Back to Hot Spots', hot_spots_path %>
        <% end %>
      </p>
      
    </div>
  </div>
</div>