config/routes.rb
Travel::Application.routes.draw do
  
  get "trips/test"
  get "users/filter"

  resources :hot_spots
  resources :notes
  resources :accommodations
  resources :destinations
  resources :trips

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pages#home'
  get "about" => 'pages#about'
  get "all" => 'users#show'
   

end

app/models/accommodation.rb
class Accommodation < ActiveRecord::Base
  attr_accessible :additional_info, :booking_end_date, :booking_start_date, :phone, :price, :reservation_number, :title, :trip_id
  belongs_to :user
  belongs_to :trip
  validates :user_id, presence: true
  validates :trip_id, presence: true
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_filter :authenticate_user!
  # GET /accommodations
  # GET /accommodations.json
  def index
    @accommodations = current_user.accommodations.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accommodations }
    end
  end

  # GET /accommodations/1
  # GET /accommodations/1.json
  def show
    @accommodation = current_user.accommodations.find(params[:id])
    @trip_idn = @accommodation.trip_id
    @trip = current_user.trips.find(@trip_idn)
    @trip_description = current_user.trips.find(@trip_idn).description

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @accommodation }
    end
  end

  # GET /accommodations/new
  # GET /accommodations/new.json
  def new
    @accommodation = current_user.accommodations.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @accommodation }
    end
  end

  # GET /accommodations/1/edit
  def edit
    @accommodation = current_user.accommodations.find(params[:id])
  end

  # POST /accommodations
  # POST /accommodations.json
  def create
    @accommodation = current_user.accommodations.new(params[:accommodation])

    respond_to do |format|
      if @accommodation.save
        format.html { redirect_to @accommodation, notice: 'Accommodation was successfully created.' }
        format.json { render json: @accommodation, status: :created, location: @accommodation }
      else
        format.html { render action: "new" }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accommodations/1
  # PUT /accommodations/1.json
  def update
    @accommodation = current_user.accommodations.find(params[:id])

    respond_to do |format|
      if @accommodation.update_attributes(params[:accommodation])
        format.html { redirect_to @accommodation, notice: 'Accommodation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accommodations/1
  # DELETE /accommodations/1.json
  def destroy
    @accommodation = current_user.accommodations.find(params[:id])
    @accommodation.destroy

    respond_to do |format|
      format.html { redirect_to accommodations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
	
end

app/views/accommodations/_accommodation.html.erb
<div class="box">
	<p><span class="accommodation_label">Accommodation:</span> <b><%= accommodation.title %></b>
	</p>

	<p>
		<% if !accommodation.reservation_number.empty? %>
			<b>Reservation #</b> <%= accommodation.reservation_number %>
		<% end %>
	</p>

	<p>
		<b>Date:</b> <%= accommodation.booking_start_date %> to <%= accommodation.booking_end_date %>
	</p>

	<p>
		<% if !accommodation.phone.empty? %>
			<b>Phone:</b> <%= accommodation.phone %>
		<% end %>
	</P>

	<p>
		<% if !accommodation.price.empty? %>
			<b>Price:</b> <%= accommodation.price %>
		<% end %>
	</p>

	<p>
		<% if !accommodation.additional_info.empty? %>
			<b>Other:</b> <%= accommodation.additional_info %>
		<% end %>
	</p>
	<p>
		<% trip_idn = current_user.trips.find(accommodation.trip_id) %>
		<em>Associated with <b><%= link_to current_user.trips.find(trip_idn).description, trip_idn %></b></em>
	</p>

	<p>
		<% if current_user == accommodation.user %>
			<%= link_to 'Show', accommodation %> |
			<%= link_to 'Edit', edit_accommodation_path(accommodation) %> |
			<%= link_to 'Destroy', accommodation, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>
</div>

app/views/accommodations/_form.html.erb
<%= simple_form_for(@accommodation, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :reservation_number %>
    <%= f.input :booking_start_date %>
    <%= f.input :booking_end_date %>
    <%= f.input :phone %>
    <%= f.input :price %>
    <%= f.input :additional_info, as: :text, input_html: { rows: '3'} %>
    <%= f.association :trip, collection: current_user.trips.all, label_method: :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accommodations/edit.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">

			<h2>Editing accommodation</h2>

			<%= render 'form' %>

			<%= link_to 'Show', @accommodation %> |
			<%= link_to 'Back', accommodations_path %>

		</div>
	</div>
</div>

app/views/accommodations/index.html.erb
<div id="container">
  <%= render @accommodations %>
</div>

app/views/accommodations/new.html.erb
<div class="row">
	<div class="span7 offset1">
		<div class="well">

			<h2>New Accommodation</h2>

			<%= render 'form' %>

			<%= link_to 'Back', accommodations_path %>
		</div>
	</div>
</div>

app/views/accommodations/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">

      <p>
        <b>Title:</b>
        <%= @accommodation.title %>
      </p>

      <p>
        <% if !@accommodation.reservation_number.empty? %>
          <b>Reservation #</b><%= @accommodation.reservation_number %>
        <% end %>
      </p>

      <p>
        <b>Dates:</b>
            <%= @accommodation.booking_start_date %>  to <%= @accommodation.booking_end_date %>
      </p>

      <p>
        <% if !@accommodation.phone.empty? %>
          <b>Phone:</b>
          <%= @accommodation.phone %>
        <% end %>
      </p>

      <p>
        <% if !@accommodation.price.empty? %>
          <b>Price:</b>
          <%= @accommodation.price %>
        <% end %>
      </p>

      <p>
        <% if !@accommodation.additional_info.empty? %>
          <b>Additional info:</b>
          <%= @accommodation.additional_info %>
        <% end %>
      </p>

      <p>
        <em>Associated with <b><%= link_to @trip_description, @trip %></b><br />
          Created by <%= @accommodation.user.username %></em>
      </p>

      <p>
        <% if current_user == @accommodation.user %>
        <%= link_to 'Edit', edit_accommodation_path(@accommodation) %> |
        <%= link_to 'Back to Accommodations', accommodations_path %>
        <% end %>
      </p>

    </div>
  </div>
</div>