config/routes.rb
Travel::Application.routes.draw do
  
  get "trips/test"
  get "users/filter"

  resources :hot_spots
  resources :notes
  resources :accommodations
  resources :destinations
  resources :trips

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  root :to => 'pages#home'
  get "about" => 'pages#about'
  get "all" => 'users#show'
   

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
 	<div class="navbar-inner">
 		<div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
 			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
 				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
 				<span class="icon-bar"></span>
			</a>
     
    <!-- Be sure to leave the brand out there if you want it shown <a class="brand" href="#">ADAMinterest</a>-->
 			<%= link_to "On Our Way", root_path, class: "brand" %>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
   		<div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
	    	<ul class="nav">
	    		<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
			</ul>
			<ul class="nav pull-right">
	    		<% if user_signed_in? %>
	    			<li class="dropdown">
	    				<a class="dropdown-toggle" data-toggle="dropdown" href="#">Add
	    					<b class="caret"></b>
	    				</a>
	    				<ul class="dropdown-menu add_new">
		    				<li><%= link_to "New Trip", new_trip_path %></li>
		    				<li><%= link_to "New Accommodation", new_accommodation_path %></li>
		    				<li><%= link_to "New Hot Spot", new_hot_spot_path %></li>
		    				<li><%= link_to "New Note", new_note_path %></li>
	    				</ul>
	    			</li>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign In", new_user_session_path %></li>
				<% end %>

			</ul>
   		</div>
     
   	</div>
  </div>
</div>

app/views/layouts/_left_nav.html.erb
<span class="label label-inverse nav_header">MY TRIPS</span>

<% if user_signed_in? %>

	<% @trips = current_user.trips %>

    <% @trips.each do |trip| %>
    <% trip.description %>
  	<% end %>

	<p>
		<!--<span class="lead">Trips</span>-->
		
		<span class="btn btn-nav btn-success btn-block">
			<%= link_to "All Trips", trips_path %>
		</span>
		
		<% @trips.each do |trip| %>
		<span class="btn btn-nav btn-primary btn-block">
			<%= link_to trip.description, trip %>
		</span>
		
		<% end %>

	</p>

	<p>
		<!--<span class="lead">Type</span>-->
		<span class="btn btn-nav btn-success btn-block">
			<%= link_to "All Types", all_path %>
		</span>
		<span class="btn btn-nav btn-info btn-block">
			<%= link_to "All Accommodations", accommodations_path %>
		</span> 
		<span class="btn btn-nav btn-info btn-block">
			<%= link_to "All Hot Spots", hot_spots_path %>
		</span>
		<span class="btn btn-nav btn-info btn-block">
			<%= link_to "All Notes", notes_path %>
		</span>
	</p>

<% else %>

	<p>Please <%= link_to "create an account", new_user_registration_path %> to get started or <%= link_to "sign in", new_user_session_path %>.</p>

<% end %>

app/views/layouts/_right_nav.html.erb
<span class="label label-inverse nav_header">ADD NEW</span>

<div align="center">

<p><%= link_to "Trip", new_trip_path, class: "btn btn-success btn-block" %>

	<%= link_to "Accommodation", new_accommodation_path, class: "btn btn-success btn-block" %> <%= link_to "Hot Spot", new_hot_spot_path, class: "btn btn-success btn-block" %> <%= link_to "Note", new_note_path, class: "btn btn-success btn-block" %>
</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>On Our Way</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
<%= render 'layouts/header' %>

<% if user_signed_in? %>
	
	<div class="row-fluid">
		
		<div class="span3" >

			<%= render 'layouts/left_nav' %>
	
			<!--<%= render 'layouts/right_nav' %>-->
		</div>

		<div class="span9">
			<% flash.each do |name,msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %> 

			<%= yield %>
		</div>

	</div>

<% else %>

<div >
	<% flash.each do |name,msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %> 

	<%= yield %>
	
</div>

<% end %>

</div>

</body>
</html>